version: '3.3'
services:
    node-exporter:
        network_mode: host
        pid: host
        volumes:
            - '/:/host:ro,rslave'
        image: 'quay.io/prometheus/node-exporter:latest'
        restart: always
        expose:
            - 9100

    prometheus:
        container_name: prometheus
        ports:
            - '9090:9090'
        volumes:
            - './prometheus.yml:/etc/prometheus/prometheus.yml'
        image: prom/prometheus
        restart: always

    grafana:
        container_name: grafana
        ports:
            - '3000:3000'
        image: grafana/grafana
        restart: always
