global:
  scrape_interval: 10s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] ## change localhost to static ip or hostname (localhost is not working in this step!)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100'] ## change localhost to static ip or hostname
