version: '2'

volumes:
  pihole:
  dnsmasq:

networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: enp1s0
    ipam:
      driver: default
      config:
       - subnet: 192.168.178.0/24
         gateway: 192.168.178.1

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: ${HOSTNAME}
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: ${ServerIP}
      WEB_PORT: 81
      WEBPASSWORD: ${WEBPASSWORD}
      TZ: ${TZ}
      DNS1: 192.168.178.253 # Hardcoded to our Unbound server
      DNSSEC: "true" # Enable DNSSEC
      DNSMASQ_LISTENING: local
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      macvlan_network:
        ipv4_address: 192.168.178.254
    restart: always

  unbound:
    image: klutchell/unbound:latest
    ports:
      - '5053:5053/tcp'
      - '5053:5053/udp'
    networks:
      macvlan_network:
        ipv4_address: 192.168.178.253
    restart: always
