alerting:
  gotify:
    server-url: "http://localhost:8680"
    token: "gotify-token"

default-endpoint: &defaults
  interval: 5m
  client:
    insecure: true
    timeout: 30s
  ui:
    hide-hostname: true
  conditions:
    - "[CONNECTED] == true"
  alerts:
    - type: gotify
      enabled: true
      failure-threshold: 1
      success-threshold: 5
      send-on-resolved: true

endpoints:
  - name: Proxy
    <<: *defaults
    url: "icmp://nginx_proxy_manager"

  - name: Homebridge
    group: SmartHome
    <<: *defaults
    url: "tcp://url:port"

  - name: zigbee2mqtt
    group: SmartHome
    <<: *defaults
    url: "tcp://url:port"

  - name: mqtt-broker
    group: SmartHome
    <<: *defaults
    url: "tcp://url:port"

  - name: Nextcloud
    <<: *defaults
    url: "icmp://nextcloud_web"

  - name: Gotify
    group: Notification
    <<: *defaults
    url: "tcp://url:port"

  - name: Gotify-Firebase
    group: Notification
    <<: *defaults
    url: "tcp://url:port"

  - name: Node-RED
    group: SmartHome
    <<: *defaults
    url: "tcp://url:port"
