version: '3'

services:
  db:
    container_name: nextcloud_mariadb
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    container_name: nextcloud_redis
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud_app
    image: nextcloud:${NEXTCLOUD_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXTCLOUD_VERSION=${NEXTCLOUD_VERSION}
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
      - LETSENCRYPT_EMAIL=
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
      - smtp.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default
    dns:
      - 1.1.1.1
      - 8.8.8.8

  cron:
    container_name: nextcloud_cron
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    volumes:
      - nextcloud:/var/www/html
    env_file:
      - db.env
      - smtp.env
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    container_name: nextcloud_proxy
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier: