################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up

# simple docker-compose up -d is enough - node red is running on port 1880
################################################################################
version: "3.7"

services:
  node-red:
    restart: always
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Berlin
    network_mode: host
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:

networks:
  node-red-net: