version: "3"
services:
  toogoodtogo-watcher:
    image: marklagendijk/toogoodtogo-watcher
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./toogoodtogo-watcher:/home/node/.config/toogoodtogo-watcher-nodejs
  
  # This will make Apprise reachable on apprise:8080/8085 for the other Docker Compose containers
  apprise:
    image: caronc/apprise:latest
    ports: 
      - "8085:8080"